services:
  - type: web
    name: mat-backend
    env: docker
    dockerfilePath: ./WorkshopApi/Dockerfile
    dockerContext: ./WorkshopApi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mattest
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://mat-frontend.onrender.com
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
